### ISSUE TITLE
Changing [string] to string[] in index.d.ts

### ISSUE THREAD

**Issue by kontheocharis** [sarkistlt/mongoose-schema-to-graphql#24]
Hi,

In the Typescript declaration file, shouldn't the `exclude` field in the type `ConfigurationObject` be a `string[]` (string array) instead of a `[string]` (tuple with one element of type string)? If the latter is used (which it is), Typescript throws an error when having more than one element in the array (i.e. when excluding multiple fields).

Basically, shouldn't this
`exclude?: RegExp | [string],`
be changed to this
`exclude?: RegExp | string[],`

Thanks.

**Comment by sarkistlt** [comment]
yes you right, fixed, thanks!
