### ISSUE TITLE
Grapiql example

### ISSUE THREAD

**Issue by anoopsinghbayes** [sarkistlt/mongoose-schema-to-graphql#4]
Great work.
can you provide an example how can we expose these graphql types through [graphiql](https://github.com/graphql/graphiql) so that it can be consumed by the UI

**Comment by sarkistlt** [comment]
Hi, thanks! What kind of example would you like to see? Because with graphiql it will be exactly the same API like created directly with GraphQL types like [here](http://cms-demo.web4fly.com/graphql), so the ways to iterate with UI will be exactly the same as well.

**Comment by anoopsinghbayes** [comment]
Ok this is what i understood after going through your code 

1. one has to write there own resolvers to actually fetch the data through mongoose.(This is what i mean by example in graphiql where you actually fetch the data from mongoose model's).
2. The Generated Schema does not defines the [arguments](http://graphql.org/learn/queries/)(Check the arguments part.) which it can accept to make the actual queries ,the "select" part in the query.

correct me if i am wrong.

**Comment by sarkistlt** [comment]
Got it, link above wasn't example of how to use this module it was just example of graphQL API.

[Here the simple example](https://gist.github.com/sarkistlt/09b6ea043f27faad4cec99b6c1a5fb34) pure graphQL without feathersjs (as on link above). 

We are basically using mongose methodes for resolvers, pretty common approach.
